import type { MigrationInterface, QueryRunner } from "typeorm";

export class Init1779043105294 implements MigrationInterface {
  name = "Init1779043105294";

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_likes" DROP CONSTRAINT "FK_9b9a7fc5eeff133cf71b8e06a7b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_likes" DROP CONSTRAINT "FK_b40d37469c501092203d285af80"`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_bdba9a10c64ff58d36b09e3ac45"`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_2073bf518ef7017ec19319a65e5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "comments" DROP CONSTRAINT "FK_db00768f42c38c5617d3ad4e52b"`,
    );
    await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_7689491fe4377a8090576a799a0"`);
    await queryRunner.query(`DROP TABLE "videos"`);
    await queryRunner.query(`DROP INDEX "public"."sessions_user_id_idx"`);
    await queryRunner.query(`DROP INDEX "public"."sessions_expires_at_idx"`);
    await queryRunner.query(`DROP TABLE "sessions"`);
    await queryRunner.query(`DROP INDEX "public"."post_likes_post_id_status_idx"`);
    await queryRunner.query(`DROP TABLE "post_likes"`);
    await queryRunner.query(`DROP TYPE "public"."post_likes_status_enum"`);
    await queryRunner.query(`DROP INDEX "public"."comment_likes_comment_id_status_idx"`);
    await queryRunner.query(`DROP TABLE "comment_likes"`);
    await queryRunner.query(`DROP TYPE "public"."comment_likes_status_enum"`);
    await queryRunner.query(`DROP INDEX "public"."comments_post_id_created_at_idx"`);
    await queryRunner.query(`DROP TABLE "comments"`);
    await queryRunner.query(`DROP INDEX "public"."posts_blog_id_idx"`);
    await queryRunner.query(`DROP TABLE "posts"`);
    await queryRunner.query(`DROP INDEX "public"."users_password_recovery_code_idx"`);
    await queryRunner.query(`DROP INDEX "public"."users_email_confirmation_code_idx"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    await queryRunner.query(`DROP TABLE "blogs"`);
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "blogs" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "description" text NOT NULL, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_membership" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "website_url" text NOT NULL, CONSTRAINT "PK_e113335f11c926da929a625f118" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."users_role_enum" AS ENUM('superAdmin', 'admin', 'user')`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" text NOT NULL, "email_confirmation_code" text, "email_confirmation_expires_at" TIMESTAMP WITH TIME ZONE, "email_is_confirmed" boolean NOT NULL DEFAULT true, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "login" text NOT NULL, "password_hash" text NOT NULL, "password_recovery_code" text, "password_recovery_expires_at" TIMESTAMP WITH TIME ZONE, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_2d443082eccd5198f95f2a36e2c" UNIQUE ("login"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "users_email_confirmation_code_idx" ON "users" ("email_confirmation_code") WHERE "email_confirmation_code" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX "users_password_recovery_code_idx" ON "users" ("password_recovery_code") WHERE "password_recovery_code" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE TABLE "posts" ("blog_id" integer NOT NULL, "blog_name" text NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dislikes_count" integer NOT NULL DEFAULT '0', "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "likes_count" integer NOT NULL DEFAULT '0', "short_description" text NOT NULL, "title" text NOT NULL, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "posts_blog_id_idx" ON "posts" ("blog_id") `);
    await queryRunner.query(
      `CREATE TABLE "comments" ("commentator_user_id" integer NOT NULL, "commentator_user_login" text NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dislikes_count" integer NOT NULL DEFAULT '0', "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "likes_count" integer NOT NULL DEFAULT '0', "post_id" integer NOT NULL, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "comments_post_id_created_at_idx" ON "comments" ("post_id", "created_at") `,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."comment_likes_status_enum" AS ENUM('Like', 'Dislike')`,
    );
    await queryRunner.query(
      `CREATE TABLE "comment_likes" ("comment_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "status" "public"."comment_likes_status_enum" NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "UQ_660059072f131c773be5f37c475" UNIQUE ("comment_id", "user_id"), CONSTRAINT "PK_2c299aaf1f903c45ee7e6c7b419" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "comment_likes_comment_id_status_idx" ON "comment_likes" ("comment_id", "status") `,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."post_likes_status_enum" AS ENUM('Like', 'Dislike')`,
    );
    await queryRunner.query(
      `CREATE TABLE "post_likes" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "post_id" integer NOT NULL, "status" "public"."post_likes_status_enum" NOT NULL, "user_id" integer NOT NULL, "user_login" text NOT NULL, CONSTRAINT "UQ_8f64693922a9e8c4e2605850d0b" UNIQUE ("post_id", "user_id"), CONSTRAINT "PK_e4ac7cb9daf243939c6eabb2e0d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "post_likes_post_id_status_idx" ON "post_likes" ("post_id", "status") `,
    );
    await queryRunner.query(
      `CREATE TABLE "sessions" ("device_id" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "ip" text NOT NULL, "last_active_at" TIMESTAMP WITH TIME ZONE NOT NULL, "title" text NOT NULL, "token_jti" text NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "UQ_9d7e9a6625486f24cf0752a5f0e" UNIQUE ("device_id", "user_id"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "sessions_expires_at_idx" ON "sessions" ("expires_at") `);
    await queryRunner.query(`CREATE INDEX "sessions_user_id_idx" ON "sessions" ("user_id") `);
    await queryRunner.query(
      `CREATE TABLE "videos" ("author" text NOT NULL, "available_resolutions" text array NOT NULL, "can_be_downloaded" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "min_age_restriction" integer, "publication_date" TIMESTAMP WITH TIME ZONE NOT NULL, "title" text NOT NULL, CONSTRAINT "PK_e4c86c0cf95aff16e9fb8220f6b" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "posts" ADD CONSTRAINT "FK_7689491fe4377a8090576a799a0" FOREIGN KEY ("blog_id") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "comments" ADD CONSTRAINT "FK_db00768f42c38c5617d3ad4e52b" FOREIGN KEY ("commentator_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_2073bf518ef7017ec19319a65e5" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_bdba9a10c64ff58d36b09e3ac45" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_likes" ADD CONSTRAINT "FK_b40d37469c501092203d285af80" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "post_likes" ADD CONSTRAINT "FK_9b9a7fc5eeff133cf71b8e06a7b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }
}
