import type { MigrationInterface, QueryRunner } from "typeorm";

export class AddQuizGames1779988800000 implements MigrationInterface {
  name = "AddQuizGames1779988800000";

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "quiz_game_answers"`);
    await queryRunner.query(`DROP TABLE "quiz_game_questions"`);
    await queryRunner.query(`DROP TABLE "quiz_game_pairs"`);
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "quiz_game_pairs" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "status" text NOT NULL,
        "first_player_user_id" integer NOT NULL,
        "second_player_user_id" integer,
        "first_player_score" integer NOT NULL DEFAULT 0,
        "second_player_score" integer NOT NULL DEFAULT 0,
        "first_player_finished_at" TIMESTAMP WITH TIME ZONE,
        "second_player_finished_at" TIMESTAMP WITH TIME ZONE,
        "pair_created_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "start_game_date" TIMESTAMP WITH TIME ZONE,
        "finish_game_date" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_quiz_game_pairs_id" PRIMARY KEY ("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_status" ON "quiz_game_pairs" ("status")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_first" ON "quiz_game_pairs" ("first_player_user_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_second" ON "quiz_game_pairs" ("second_player_user_id")`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_questions" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "order_index" integer NOT NULL,
        CONSTRAINT "PK_quiz_game_questions_id" PRIMARY KEY ("id"),
        CONSTRAINT "uq_quiz_game_questions_game_order" UNIQUE ("game_id", "order_index"),
        CONSTRAINT "fk_quiz_game_questions_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_questions_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_answers" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "player_user_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "answer_status" text NOT NULL,
        "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_quiz_game_answers_id" PRIMARY KEY ("id"),
        CONSTRAINT "fk_quiz_game_answers_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_answers_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_answers_lookup" ON "quiz_game_answers" ("game_id", "player_user_id")`,
    );
  }
}
