import type { MigrationInterface, QueryRunner } from "typeorm";

export class AddQuizQuestions1779901300050 implements MigrationInterface {
  name = "AddQuizQuestions1779901300050";

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "quiz_questions"`);
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "quiz_questions" ("body" text NOT NULL, "correct_answers" jsonb NOT NULL DEFAULT '[]'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "published" boolean NOT NULL DEFAULT false, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_quiz_questions_id" PRIMARY KEY ("id"))`,
    );
  }
}
