import type { MigrationInterface, QueryRunner } from "typeorm";

export class NormalizeQuizSchema1780000000000 implements MigrationInterface {
  name = "NormalizeQuizSchema1780000000000";

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_quiz_game_answers_player"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_answers"`);

    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_questions"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_quiz_game_players_game"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_quiz_game_players_user"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_players"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_quiz_game_pairs_status"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_pairs"`);

    await queryRunner.query(`DROP INDEX IF EXISTS "idx_quiz_question_correct_answers_question"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_question_correct_answers"`);

    await queryRunner.query(
      `ALTER TABLE "quiz_questions" ADD COLUMN "correct_answers" jsonb NOT NULL DEFAULT '[]'::jsonb`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_pairs" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "status" text NOT NULL,
        "first_player_user_id" integer NOT NULL,
        "second_player_user_id" integer,
        "first_player_score" integer NOT NULL DEFAULT 0,
        "second_player_score" integer NOT NULL DEFAULT 0,
        "first_player_finished_at" TIMESTAMP WITH TIME ZONE,
        "second_player_finished_at" TIMESTAMP WITH TIME ZONE,
        "pair_created_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "start_game_date" TIMESTAMP WITH TIME ZONE,
        "finish_game_date" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_quiz_game_pairs_id" PRIMARY KEY ("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_status" ON "quiz_game_pairs" ("status")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_first" ON "quiz_game_pairs" ("first_player_user_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_second" ON "quiz_game_pairs" ("second_player_user_id")`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_questions" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "order_index" integer NOT NULL,
        CONSTRAINT "PK_quiz_game_questions_id" PRIMARY KEY ("id"),
        CONSTRAINT "uq_quiz_game_questions_game_order" UNIQUE ("game_id", "order_index"),
        CONSTRAINT "fk_quiz_game_questions_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_questions_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_answers" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "player_user_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "answer_status" text NOT NULL,
        "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_quiz_game_answers_id" PRIMARY KEY ("id"),
        CONSTRAINT "fk_quiz_game_answers_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_answers_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_answers_lookup" ON "quiz_game_answers" ("game_id", "player_user_id")`,
    );
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_answers"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_questions"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "quiz_game_pairs"`);

    await queryRunner.query(`ALTER TABLE "quiz_questions" DROP COLUMN IF EXISTS "correct_answers"`);

    await queryRunner.query(
      `CREATE TABLE "quiz_question_correct_answers" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "question_id" integer NOT NULL,
        "answer_text" text NOT NULL,
        CONSTRAINT "PK_quiz_question_correct_answers_id" PRIMARY KEY ("id"),
        CONSTRAINT "fk_quiz_question_correct_answers_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id") ON DELETE CASCADE
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_question_correct_answers_question" ON "quiz_question_correct_answers" ("question_id")`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_pairs" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "status" text NOT NULL,
        "pair_created_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "start_game_date" TIMESTAMP WITH TIME ZONE,
        "finish_game_date" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_quiz_game_pairs_id" PRIMARY KEY ("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_pairs_status" ON "quiz_game_pairs" ("status")`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_players" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "user_id" integer NOT NULL,
        "position" smallint NOT NULL,
        "score" integer NOT NULL DEFAULT 0,
        "finished_at" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_quiz_game_players_id" PRIMARY KEY ("id"),
        CONSTRAINT "uq_quiz_game_players_game_position" UNIQUE ("game_id", "position"),
        CONSTRAINT "uq_quiz_game_players_game_user" UNIQUE ("game_id", "user_id"),
        CONSTRAINT "ck_quiz_game_players_position" CHECK ("position" IN (1, 2)),
        CONSTRAINT "fk_quiz_game_players_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_players_game" ON "quiz_game_players" ("game_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_players_user" ON "quiz_game_players" ("user_id")`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_questions" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "game_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "order_index" integer NOT NULL,
        CONSTRAINT "PK_quiz_game_questions_id" PRIMARY KEY ("id"),
        CONSTRAINT "uq_quiz_game_questions_game_order" UNIQUE ("game_id", "order_index"),
        CONSTRAINT "fk_quiz_game_questions_game" FOREIGN KEY ("game_id") REFERENCES "quiz_game_pairs"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_questions_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );

    await queryRunner.query(
      `CREATE TABLE "quiz_game_answers" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "player_id" integer NOT NULL,
        "question_id" integer NOT NULL,
        "answer_status" text NOT NULL,
        "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_quiz_game_answers_id" PRIMARY KEY ("id"),
        CONSTRAINT "fk_quiz_game_answers_player" FOREIGN KEY ("player_id") REFERENCES "quiz_game_players"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_quiz_game_answers_question" FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id")
      )`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_quiz_game_answers_player" ON "quiz_game_answers" ("player_id")`,
    );
  }
}
